config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  root 'posts#index'
  namespace :user do
    resources :posts
    resources :profiles
    get '/follows', to: 'follows#follow', as: 'user_follows'
    get '/followers', to: 'follows#follower', as: 'user_followers'
  end
  post '/follows', to: 'follows#create', as: 'follows'
  post '/unfollows', to: 'follows#destroy', as: 'unfollows'
  get '/all_users', to: 'users#index', as: 'all_users'
  get '/user/:id', to: 'users#show', as: 'select_user_profile'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates_presence_of :unique_name
  validates_uniqueness_of :unique_name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :sender, class_name: "user"
  belongs_to :receiver, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  has_many_attached :images
  has_many_attached :vedios

  has_many :likes
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  enum gender: {'male': '0', 'female': '1'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes

  has_one :profile

  has_many :followers
  has_many :followables

  has_many :sent_messages, foreign_key: "sender", class_name: "Message"
  has_many :received_messages, foreign_key: "receiver", class_name: "Message"

  acts_as_followable
  acts_as_follower
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)

    respond_to do |format|
      format.js { render partial: 'follows/create' }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)

    respond_to do |format|
      format.js { render partial: 'follows/destroy' }
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.create(post_id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.js { render partial: 'likes/create' }
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:id]).destroy
    respond_to do |format|
      format.js { render partial: 'likes/destroy' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !(current_user.profile.present?)
      redirect_to new_user_profile_path
    else
      @post = Post.new
      @posts = Post.all
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(path)
    request.path == path ? "active" : "nav-item"

  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_create.html.erb
<%= link_to like_path(@like.post_id), method: :delete, remote: true, class: 'btn background_none shadow-none col-lg-6 d-flex align-items-center justify-content-center mt-2 mb-2' do %>
  <i class="fa fa-thumbs-up  like_comment mr-2" aria-hidden="true"></i>
  <span>Unlike</span>
<% end %>

app/views/likes/_create.js.erb
$('#like').html("<%= j render 'likes/create.html' %>")

app/views/likes/_destroy.html.erb
<%= link_to likes_path(id: @like.post_id), method: :post, remote: true, class: 'btn background_none shadow-none col-lg-6 d-flex align-items-center justify-content-center mt-2 mb-2' do %>
  <i class="fa fa-thumbs-o-up like_comment mr-2" aria-hidden="true"></i>
  <span>Like</span>
<% end %>

app/views/likes/_destroy.js.erb
$('#like').html("<%= j render 'likes/destroy.html' %>")

app/views/likes/_like.html.erb
<%= link_to likes_path(id: post), method: :post, remote: true, class: 'btn background_none shadow-none col-lg-6 d-flex align-items-center justify-content-center mt-2 mb-2' do %>
  <i class="fa fa-thumbs-o-up like_comment mr-2" aria-hidden="true"></i>
  <span>Like</span>
<% end %>

app/views/likes/_unlike.html.erb
<%= link_to like_path(post), method: :delete, remote: true, class: 'btn background_none shadow-none col-lg-6 d-flex align-items-center justify-content-center mt-2 mb-2' do %>
  <i class="fa fa-thumbs-up  like_comment mr-2" aria-hidden="true"></i>
  <span>Unlike</span>
<% end %>