config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  root 'posts#index'
  namespace :user do
    resources :posts
    resources :profiles
    get '/follows', to: 'follows#follow', as: 'user_follows'
    get '/followers', to: 'follows#follower', as: 'user_followers'
  end
  post '/follows', to: 'follows#create', as: 'follows'
  post '/unfollows', to: 'follows#destroy', as: 'unfollows'
  get '/all_users', to: 'users#index', as: 'all_users'
  get '/user/:id', to: 'users#show', as: 'select_user_profile'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates_presence_of :unique_name
  validates_uniqueness_of :unique_name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :sender, class_name: "user"
  belongs_to :receiver, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  has_many_attached :images
  has_many_attached :vedios

  has_many :likes
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  enum gender: {'male': '0', 'female': '1'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes

  has_one :profile

  has_many :followers
  has_many :followables

  has_many :sent_messages, foreign_key: "sender", class_name: "Message"
  has_many :received_messages, foreign_key: "receiver", class_name: "Message"

  acts_as_followable
  acts_as_follower
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)

    respond_to do |format|
      format.js { render partial: 'follows/create' }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)

    respond_to do |format|
      format.js { render partial: 'follows/destroy' }
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.create(post_id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.js { render partial: 'likes/create' }
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:id]).destroy
    respond_to do |format|
      format.js { render partial: 'likes/destroy' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !(current_user.profile.present?)
      redirect_to new_user_profile_path
    else
      @post = Post.new
      @posts = Post.all
    end

  end

end

app/controllers/user/follows_controller.rb
class User::FollowsController < ApplicationController
  before_action :authenticate_user!

  def follower
    @users = current_user.all_follows
  end

  def follow
    @users = current_user.all_following
  end

end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = current_user.posts
  end

  def show; end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if (@post.save)
      flash[:notice] = 'post create successfully'
      redirect_to root_path
    else
      flash[:alert] = @post.errors
      redirect_to root_path
    end
  end

  def edit

  end

  def update
    if(@post.update(post_params))
      flash[:notice] = "Post update successfully"
    else
      flash[:alert] = @post.errors
    end
  end

  def destroy

    if(@post.destroy)
      flash[:notice] = "Post delete successfully!!"
    else
      flash[:alert] = @post.errors
    end

  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, images: [])
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      flash[:notice] = "profile created!"
      redirect_to all_users_path
    else
      flash[:alert] = @profile.errors
      render 'new'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:user_name, :first_name, :last_name, :address,
                                 :city, :country, :phone, :company_name,
                                 :company_bio, :gender, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(path)
    request.path == path ? "active" : "nav-item"

  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user/follows_helper.rb
module User::FollowsHelper
end

app/helpers/user/profiles_helper.rb
module User::ProfilesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render 'shared/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render 'shared/left_sidebar' %>
    <div class="col-lg-8">
      <h2> Heading page</h2>
      <% @users.each do |user| %>
        <% if user.id != current_user.id && user.profile.present? %>
          <div class="card boxes_main mb-3 p-4">
            <div class="name_here mb-2 d-flex align-items-center">
              <a href="" class="post_img_area_main float-left">
                <%= image_tag user.profile.present? && user.profile.avatar.present? ? user.profile.avatar : 'profile.jpg', class: "img-fluid post_img_area" %>
              </a>
              <div class="float-left ml-2 mb-1 d-flex flex-column">
                <%= link_to select_user_profile_path(user) do %>
                  <h3 class="ml-2"><%= "#{user.profile.user_name} (#{user.profile.first_name} #{user.profile.last_name})" if user.profile.present? %></h3>
                <% end %>
                <p class="text-muted m-0 small_font ml-2"><%= "#{user.profile.company_bio}" if user.profile.present? %></p>
              </div>
              <div id="follow" class="float-right">
                <%= render 'shared/follow_form', user: user %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if Profile.all.count < 2 %>
        <p>There are no user to display</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<main class="default-transition" style="opacity: 1;">
  <%= render 'shared/header' %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="mb-4">
          <h1><%= @user.profile.user_name %></h1>
          <h5><%= @user.profile.company_name %></h5>
          <p><%= @user.profile.company_bio %></p>

          <%= link_to 'Message', '#', class: 'btn btn-outline-primary btn-sm' %>
          <div id="follow" class="float-right mr-50">
            <%= render 'shared/follow_form', user: @user %>
          </div>
        </div>
        <div class="tab-content">
          <div class="tab-pane show active" id="first" role="tabpanel" aria-labelledby="first-tab">
            <div class="row">
              <div class="col-12 mb-5">


              </div>
              <%= render 'shared/left_sidebar' %>
              <div class="col-lg-8">
                <% @user.posts.each do |post| %>
                  <%= render 'shared/post_card', post: post %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>