config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  root 'posts#index'
  namespace :user do
    resources :posts
    resources :profiles
    get '/follows', to: 'follows#follow', as: 'user_follows'
    get '/followers', to: 'follows#follower', as: 'user_followers'
  end
  post '/follows', to: 'follows#create', as: 'follows'
  post '/unfollows', to: 'follows#destroy', as: 'unfollows'
  get '/all_users', to: 'users#index', as: 'all_users'
  get '/user/:id', to: 'users#show', as: 'select_user_profile'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates_presence_of :unique_name
  validates_uniqueness_of :unique_name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :sender, class_name: "user"
  belongs_to :receiver, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  has_many_attached :images
  has_many_attached :vedios

  has_many :likes
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  enum gender: {'male': '0', 'female': '1'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes

  has_one :profile

  has_many :followers
  has_many :followables

  has_many :sent_messages, foreign_key: "sender", class_name: "Message"
  has_many :received_messages, foreign_key: "receiver", class_name: "Message"

  acts_as_followable
  acts_as_follower
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "comment add successfully"
      respond_to do |format|
        format.js { render partial: 'comments/create' }
      end
    else
      flash[:alert] = @comment.errors
      redirect_to root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)

    respond_to do |format|
      format.js { render partial: 'follows/create' }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)

    respond_to do |format|
      format.js { render partial: 'follows/destroy' }
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.create(post_id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.js { render partial: 'likes/create' }
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:id]).destroy
    respond_to do |format|
      format.js { render partial: 'likes/destroy' }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    byebug
  end

  private
  def message_params
    params.require(:messages).permit(:receiver_id, :content, :chat_room_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !(current_user.profile.present?)
      redirect_to new_user_profile_path
    else
      @post = Post.new
      @posts = Post.all
    end

  end

end

app/controllers/user/follows_controller.rb
class User::FollowsController < ApplicationController
  before_action :authenticate_user!

  def follower
    @users = current_user.all_follows
  end

  def follow
    @users = current_user.all_following
  end

end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = current_user.posts
  end

  def show; end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if (@post.save)
      flash[:notice] = 'post create successfully'
      redirect_to root_path
    else
      flash[:alert] = @post.errors
      redirect_to root_path
    end
  end

  def edit

  end

  def update
    if(@post.update(post_params))
      flash[:notice] = "Post update successfully"
    else
      flash[:alert] = @post.errors
    end
  end

  def destroy

    if(@post.destroy)
      flash[:notice] = "Post delete successfully!!"
    else
      flash[:alert] = @post.errors
    end

  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, images: [])
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      flash[:notice] = "profile created!"
      redirect_to all_users_path
    else
      flash[:alert] = @profile.errors
      render 'new'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:user_name, :first_name, :last_name, :address,
                                 :city, :country, :phone, :company_name,
                                 :company_bio, :gender, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(path)
    request.path == path ? "active" : "nav-item"

  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user/follows_helper.rb
module User::FollowsHelper
end

app/helpers/user/profiles_helper.rb
module User::ProfilesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/profiles/new.html.erb
<div class="container my-4">
  <div class="card boxes_main bg_bodr p-5">
    <h6 class="text-muted">USER INFORMATION</h6>
    <%= form_for(@profile, url: user_profiles_path) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>First Name</label>
          <%= f.text_field :first_name, class: 'w-100 bodr p-2',placeholder: 'first name' %>
        </div>
        <div class="col-md-6">
          <label>Last Name</label>
          <%= f.text_field :last_name, class: 'w-100 bodr p-2',placeholder: 'last name' %>
        </div>
      </div>
      <div class="row my-4">
        <div class="col-md-6">
          <label>User Name</label>
          <%= f.text_field :user_name, class: 'w-100 bodr p-2',placeholder: 'user_name' %>
        </div>
        <div class="col-md-6">
          <label>Phone</label>
          <%= f.text_field :phone, class: 'w-100 bodr p-2',placeholder: '030000000' %>
        </div>
      </div>
      <h6 class="mt-5 text-muted">ADDRESS INFORMATION</h6>
      <label>Address</label>
      <%= f.text_field :address, class: 'w-100 bodr p-2',placeholder: 'street no # 2 sabzazar' %>
      <div class="row py-4">
        <div class="col-md-6">
          <div class="d-flex flex-column">
            <label>City</label>
            <%= f.text_field :city, class: 'w-100 bodr p-2',placeholder: 'city' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="d-flex flex-column">
            <label>Country</label>
            <%= f.text_field :country, class: 'w-100 bodr p-2',placeholder: 'Pakistan' %>
          </div>
        </div>
      </div>
      <h6 class="mt-5 text-muted">COMPANY INFORMATION</h6>
      <div class="col-md-12">
        <label>Company Name</label>

        <%= f.text_field :company_name, class: 'w-100 bodr p-2',placeholder: 'Company Name' %>
      </div>
      <div class="row py-4">
        <div class="col-md-12">
          <label>Company Bio</label>
          <%= f.text_area :company_bio, class: 'w-100 bodr my-2 p-2', rows: '4'%>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <label>Gender</label>
          <%= f.select(:gender, Profile.genders.keys.map {|key| [key.humanize, key]}, {}, class: 'form-control') %>
        </div>
        <div class="col-md-6">
          <label>Avatar</label>
          <%= f.file_field :avatar, class: 'w-100  p-2',placeholder: 'last name' %>
        </div>
      </div>
      <div class="d-flex flex-row">
        <div class="d-flex">
          <button class="btn btn-primary my-2">Finish</button>
        </div>
      </div>
    <% end %>
  </div>
</div>