config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  root 'posts#index'
  namespace :user do
    resources :posts
    resources :profiles
    get '/follows', to: 'follows#follow', as: 'user_follows'
    get '/followers', to: 'follows#follower', as: 'user_followers'
  end
  post '/follows', to: 'follows#create', as: 'follows'
  post '/unfollows', to: 'follows#destroy', as: 'unfollows'
  get '/all_users', to: 'users#index', as: 'all_users'
  get '/user/:id', to: 'users#show', as: 'select_user_profile'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates_presence_of :unique_name
  validates_uniqueness_of :unique_name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :sender, class_name: "user"
  belongs_to :receiver, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  has_many_attached :images
  has_many_attached :vedios

  has_many :likes
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  enum gender: {'male': '0', 'female': '1'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes

  has_one :profile

  has_many :followers
  has_many :followables

  has_many :sent_messages, foreign_key: "sender", class_name: "Message"
  has_many :received_messages, foreign_key: "receiver", class_name: "Message"

  acts_as_followable
  acts_as_follower
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.create(post_id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.js { render partial: 'likes/create' }
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:id]).destroy
    respond_to do |format|
      format.js { render partial: 'likes/destroy' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(path)
    request.path == path ? "active" : "nav-item"

  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizProm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/alert_message' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert_message.html.erb
<% if notice.present? %>
  <div class="position-absolute z_index_up alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert.present? %>
  <div class="position-absolute z_index_up alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Error!</strong> <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_chat_container.html.erb
<div class="col-lg-4">
  <div class="card boxes_main pt-2">
    <div class="side_navigation right_side py-4">
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Shoaib Malik</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Rameen Ahsan</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Amna Arshad</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Qurat Ul Ain</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Shoaib Malik</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Rameen Ahsan</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Amna Arshad</h3>
      </a>
      <a href="" class="name_here mb-4 text-dark">
        <div class="post_img_area_main float-left">
          <img src="img/profile_img.jpg" class="img-fluid post_img_area">
        </div>
        <h3 class="float-left ml-2">Qurat Ul Ain</h3>
      </a>
    </div>
  </div>
</div>

app/views/shared/_create_post.html.erb
<div class="card boxes_main mb-3 p-4">
  <%= form_for(@post, url: user_posts_path) do |f| %>
    <%= f.text_field :content, class:"form-control add_post height_50px mb-4", placeholder: "Start a post" %>
    <div class="row d-flex justify-content-between">
      <div class="col-lg-8">
        <button class="file btn new_post_btn p-1 mr-3">
          <i class="fa fa-picture-o sky_blue_18px" aria-hidden="true"></i>
          <span class="artdeco-button__text">
            Photo
          </span>
          <%= f.file_field :images, multiple: true %>
        </button>
        <button class="file btn new_post_btn p-1">
          <i class="fa fa-youtube-play sky_blue_18px" aria-hidden="true"></i>
          <span class="artdeco-button__text">
            Video
          </span>

          <%= f.file_field :videos, multiple: true %>
        </button>
      </div>
      <div class="col-lg-4 d-flex justify-content-end">
        <%= f.submit 'Publish', class:"btn btn-outline-primary radius_custom artdeco-button__text" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_follow_form.html.erb
<% if user.followed_by?(current_user) %>
  <%= form_tag unfollows_path(user_id: user.id), method: :post, remote: true do %>
    <%= button_tag 'unfollow', class: 'btn btn-outline-secondary ml-auto' %>
  <% end %>
<% else %>
  <%= form_tag follows_path(user_id: user.id), method: :post, remote: true do %>
    <%= button_tag 'follow', class: 'btn btn-outline-success ml-auto' %>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="mb-5">
  <nav class="navbar navbar-expand-lg navbar-mainbg">
    <a class="navbar-brand navbar-logo" href="#">BuzProm</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <i class="fas fa-bars text-white"></i> </button>
    <form class="form-inline header_search ml-5">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <div class="hori-selector">
          <div class="left"></div>
          <div class="right"></div>
        </div>
        <li class= "nav-item active" >
          <%= link_to root_path do %>
            <i class="fa fa-home" aria-hidden="true"></i> New Feeds
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to root_path do %>
            <i class="fa fa-user" aria-hidden="true"></i>My Profile
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""><i class="fa fa-cog" aria-hidden="true"></i> Notification</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_left_sidebar.html.erb
<div class="col-lg-3">
  <div class="card boxes_main pt-2 mb-3">
    <ul class="side_navigation mb-5">
      <li>
        <%= link_to 'Follower', user_user_followers_path %>
      </li>
      <li>
        <%= link_to 'Following', user_user_follows_path %>
      </li>
      <li>
        <%= link_to 'All Users', all_users_path %>
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>

  <div class="card boxes_main pt-2">
    <div class="col-lg-12 col-left">
      <a href="img/profile.jpg" class="lightbox">
        <%= image_tag current_user.present? && current_user.profile.present? && current_user.profile.avatar.present? ? current_user.profile.avatar : 'profile.jpg', class:"profile_img"  %>
      </a>
      <div class="card-body">
        <div class="text-center pt-4">
          <strong>
            <h6 class="pt-2">
              <%= "#{current_user.profile.user_name}" if current_user.present? && current_user.profile.present? %>
            </h6>
          </strong>
          <small>
            <%= "#{current_user.profile.first_name} #{current_user.profile.last_name}" if current_user.present? && current_user.profile.present? %>
          </small>
        </div>
        <p class="mb-3"><%= "#{current_user.profile.company_bio}" if current_user.present? && current_user.profile.present? %>.</p>
        <p class="text-muted small_font mb-2">Location</p>
        <p class="mb-3"><%= "#{current_user.profile.city}, #{current_user.profile.country}" if current_user.present? && current_user.profile.present? %>.</p>
        <p class="text-muted small_font mb-2">Company Name</p>
        <p class="mb-3"><%= "#{current_user.profile.company_name}" if current_user.present? && current_user.profile.present? %></p>
        <p class="text-muted small_font mb-2">Email</p>
        <p class="mb-3"><%= "#{current_user.email}" if current_user.present? %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_post_card.html.erb
<div class="card boxes_main mb-3 p-4">
  <div class="name_here mb-2 d-flex align-items-center">
    <div class="post_img_area_main float-left">
      <%= image_tag post.user.profile.avatar.present? ? post.user.profile.avatar : 'profile.jpg', class: 'img-fluid post_img_area' %>
    </div>
    <div class="float-left ml-2 mb-1 d-flex flex-column">
      <h3 class="ml-2"><%= post.user.profile.user_name %></h3>
      <p class="text-muted m-0 small_font ml-2"><%= time_ago_in_words(post.created_at) %></p>
    </div>
  </div>
  <p class="p-0 m-0 mb-1"><%= post.content %></p>
  <div class="post_imgs to_show_one_image">
    <div class="row">
      <div class="col-lg-12">
        <div class="row position-relative">
          <% if post.images.present? %>
            <div class="col-lg-12 mb-2 user_multiple_img ">
              <% post.images.each do |image| %>

                <%= image_tag image, class: post.images.count > 1 ? "img-fluid float-left px-1 mb-2 height_160px" : "img-fluid w-100 height_220px img-small" %>
              <% end %>
            </div>
          <% end %>

<!--          <div class="col-lg-6 pr_1 mb_2">-->
<!--            <img src="images/bg1.jpg" class="img-fluid w-100 height_160px">-->
<!--          </div>-->
<!--          <div class="col-lg-6 pl_1">-->
<!--            <img src="images/bg2.jpg" class="img-fluid w-100 height_160px">-->
<!--          </div>-->

        </div>
      </div>
      <div class="col-lg-12">
        <div class="col-lg-12 d-flex flex-row mt-3 mb-3 border-bottom border-top" >
          <span id="like">
            <% if post.likes.find_by(user_id: current_user.id) %>
            <%= render 'likes/unlike', post: post.id %>
            <% else %>
              <%= render 'likes/like', post: post.id %>
            <% end %>
          </span>
          <div id="accordion" class="accordion col-lg-6 mt-2 mb-2">
            <button class="w-100 btn background_none shadow-none d-flex align-items-center justify-content-center" data-toggle="collapse" href="#collapseOne">
              <i class="fa fa-comment-o like_comment mr-2" aria-hidden="true"></i>
              <span>Comment</span>
            </button>
          </div>
        </div>
        <div id="accordion" class="accordion col-lg-12 my-1">
          <div id="collapseOne" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <div class="d-flex flex-row align-items-center name_here position-relative">
                <%= image_tag current_user.profile.avatar.present? ? current_user.profile.avatar : 'profile.jpg', class:"rounded-circle img-fluid post_img_area float-left mr-2", width:"40px", height:"40px" %>
                <%= form_for(@comment, url: comments_path, remote: true) do |f| %>
                  <%= f.text_field :content, class: "form-control comment_here", placeholder:"Write Comment:", id: 'comment_input'  %>
                  <%= f.number_field :post_id, value: post.id, class: 'd-none' %>
                  <%= f.submit 'Comment', class: "position-absolute top_right_send_btn text-dark" do %>
                  <% end %>
                <% end %>
              </div>
              <div id="user_comment_here">
                <% post.comments.order(created_at: :desc).each do |comment| %>
                  <div class="name_here mb-2 mt-4 d-flex">
                    <%= image_tag comment.user.profile.avatar.present? ? comment.user.profile.avatar : 'profile.jpg', class:"rounded-circle img-fluid post_img_area float-left mr-2", width:"40px", height:"40px" %>
                    <div class="float-left ml-2 mb-1 d-flex flex-column back_light_gry p-2 rounded">
                      <h3 class="ml-2 mb-2"><%= comment.user.profile.user_name %></h3>
                      <small class="float-right">skdja</small>
                      <p class="text-muted m-0 small_font ml-2"><%= comment.content %> </p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>